#!/usr/bin/env python3
# /// script
# requires-python = "==3.12.*"
# dependencies = ["pyyaml==6.0.3"]
# ///
"""Hold each dataset README's step list to the manifest that dataset actually runs.

A Protocol README describes the steps `arc run` executes. Nothing kept the two in
step, and the drift was not hypothetical: `datasets/edgar_gleif/README.md` said the
Protocol had "no opaque `command:`/shell steps" while `arcform.yaml` ran three of
them, and it said so for months. A reader deciding whether to trust a published
Dataset read the sentence, not the manifest.

The claim is not checked as prose. The README carries a GENERATED block — the step
table and the sentence about shell steps both — and this script regenerates that
block from the parsed manifest and compares it byte for byte. So the question is
never "does the README contain a phrase" but "is the README's copy of the step list
the step list". A step added, removed, renamed, or moved between `sql:`, `op:` and
`command:` changes the generated bytes and this reddens. So does an operator version
bump, because `op: parquet_export@1` and `op: parquet_export@2` are not the same step.

THE MANIFEST IS PARSED AS YAML, NEVER SCANNED AS TEXT. `arcform.yaml` is 40% comment
by line, and every comment in it mentions step names and `command:`. A grep for
`command:` in `datasets/edgar_gleif/arcform.yaml` returns 4 with no `command:` step
in the file at all. The step list is a property of the document, so it is read from
the document.

EVERY MANIFEST IS REQUIRED TO CARRY THE BLOCK. A check that quietly skips the dataset
whose README has no block would pass loudest exactly when a new Protocol shipped
undocumented, so a manifest with a README and no block is a failure, not a skip.

Every run prints how many manifests it examined out of how many it found, and those
two numbers are allowed to differ: a fault in one dataset is collected and the rest
are still held to their READMEs, so `examined 3 manifest(s) of 4 found` is a state
this check can actually reach and therefore a line a test can pin. It was not, in the
first cut — a fault returned immediately, so every run either examined all of them or
printed nothing, the two numbers were equal on every reachable input, and the line
that existed to say "this run was not vacuous" said nothing a mutation could disturb.

    check_protocol_readme.py              check; exit 1 on disagreement
    check_protocol_readme.py --write      regenerate each block in place
"""

from __future__ import annotations

import argparse
import difflib
import re
import sys
from pathlib import Path
from typing import Any

import yaml

EXIT_OK = 0
EXIT_DISAGREEMENT = 1
EXIT_ERROR = 2

OPEN_MARKER = (
    "<!-- protocol-steps: generated from arcform.yaml by "
    "scripts/check_protocol_readme.py — do not edit this block by hand -->"
)
CLOSE_MARKER = "<!-- /protocol-steps -->"

# Anchored at a line start, and every occurrence is found rather than the first: a
# second opener means the README has two blocks and there is no answer to which one
# is the step list, which is refused rather than resolved by picking one.
OPEN_RE = re.compile(r"^" + re.escape(OPEN_MARKER) + r"$", re.MULTILINE)
CLOSE_RE = re.compile(r"^" + re.escape(CLOSE_MARKER) + r"$", re.MULTILINE)


class CheckError(Exception):
    """A fault in the inputs — not a disagreement between them."""


def step_kind(step: dict[str, Any], where: str, index: int) -> str:
    """How the engine runs this step, as the manifest declares it.

    `arcform`'s loader accepts exactly one of `sql:`, `op:` and `command:` per step.
    A step declaring none or several is a manifest fault, and it is raised here
    rather than rendered as an empty cell — a README table with a blank kind column
    is a worse outcome than a refusal that says which step.
    """
    declared = [key for key in ("sql", "op", "command") if key in step]
    if len(declared) != 1:
        raise CheckError(
            f"{where}: step {index} ({step.get('name', '<unnamed>')!r}) declares "
            f"{declared or 'none'} of sql:/op:/command:; exactly one is a step"
        )
    key = declared[0]
    if key == "command":
        # The command line itself is not rendered: it is often long, frequently
        # multi-line, and what the README has to be honest about is THAT the step is
        # an opaque shell step, not which shell it runs.
        return "`command:` (shell)"
    value = step[key]
    if not isinstance(value, str) or not value.strip():
        raise CheckError(
            f"{where}: step {index} ({step.get('name', '<unnamed>')!r}) declares "
            f"`{key}:` with no value"
        )
    return f"`{key}: {value.strip()}`"


def steps_of(manifest_path: Path) -> list[tuple[str, str]]:
    """(name, kind) for every step the manifest declares, in declared order."""
    try:
        document = yaml.safe_load(manifest_path.read_text(encoding="utf-8"))
    except (OSError, yaml.YAMLError) as exc:
        raise CheckError(f"{manifest_path}: cannot be read as YAML: {exc}") from exc
    if not isinstance(document, dict):
        raise CheckError(f"{manifest_path}: is not a YAML mapping")
    steps = document.get("steps")
    if not isinstance(steps, list) or not steps:
        raise CheckError(f"{manifest_path}: declares no `steps:` list")
    out: list[tuple[str, str]] = []
    seen: set[str] = set()
    for index, step in enumerate(steps, start=1):
        if not isinstance(step, dict):
            raise CheckError(f"{manifest_path}: step {index} is not a mapping")
        name = step.get("name")
        if not isinstance(name, str) or not name.strip():
            raise CheckError(f"{manifest_path}: step {index} declares no `name:`")
        name = name.strip()
        if name in seen:
            raise CheckError(f"{manifest_path}: declares two steps named {name!r}")
        seen.add(name)
        out.append((name, step_kind(step, str(manifest_path), index)))
    return out


def shell_step_sentence(steps: list[tuple[str, str]]) -> str:
    """The claim about shell steps, DERIVED rather than written.

    This is the sentence the edgar_gleif README carried, wrong, for months. It is
    generated here so that it cannot be true when written and false later: adding a
    `command:` step rewrites it into one that names the step, and this check reddens
    until the README carries the rewrite.
    """
    shells = [name for name, kind in steps if kind == "`command:` (shell)"]
    total = len(steps)
    if not shells:
        return (
            f"All {total} steps are `sql:` models or typed `op:` operators from the "
            f"arcform catalog. This Protocol runs no opaque `command:`/shell step."
        )
    named = ", ".join(f"`{name}`" for name in shells)
    verb = "runs" if len(shells) == 1 else "run"
    return (
        f"{total} steps, of which {len(shells)} {verb} through an opaque "
        f"`command:`/shell step: {named}. A shell step is invisible to the engine's "
        f"staleness model and carries its interpreter and dependency pins inline, so "
        f"what this Protocol guarantees stops short of it."
    )


def render(steps: list[tuple[str, str]]) -> str:
    """The block body — everything between the two markers, markers included."""
    lines = [
        OPEN_MARKER,
        "",
        shell_step_sentence(steps),
        "",
        "| # | Step | How it runs |",
        "|---|---|---|",
    ]
    for index, (name, kind) in enumerate(steps, start=1):
        lines.append(f"| {index} | `{name}` | {kind} |")
    lines.extend(["", CLOSE_MARKER])
    return "\n".join(lines)


def locate_block(readme_path: Path, text: str, *, create: bool = False) -> tuple[int, int]:
    """(start, end) character offsets of the block, markers included.

    Refuses anything but exactly one opener and one closer, in that order. A README
    is prose and a marker can be mentioned in it; "the first thing that looks like
    the marker" is how a scan ends up reading a comment as the thing it describes.

    With `create`, a README carrying NO marker at all gets an empty block appended
    under its own heading, so a new Protocol's author has a remedy rather than an
    error. Where the block belongs in the document is an editorial choice, so it is
    only ever placed at the end — moving it afterwards is a normal edit, and every
    later run replaces it wherever it then sits. Ambiguity (two openers, a stray
    closer) is never repaired: it is refused, because there is no answer to which of
    two blocks is the step list.
    """
    opens = list(OPEN_RE.finditer(text))
    closes = list(CLOSE_RE.finditer(text))
    if create and not opens and not closes:
        end = len(text)
        return end, end
    if len(opens) != 1 or len(closes) != 1:
        remedy = (
            "Add one with `python scripts/check_protocol_readme.py --write`"
            if not opens and not closes
            else "Delete the extra marker(s) and leave exactly one pair"
        )
        raise CheckError(
            f"{readme_path}: needs exactly one generated step block — found "
            f"{len(opens)} opening marker(s) and {len(closes)} closing marker(s). "
            f"{remedy} (the opening marker is a single line: {OPEN_MARKER})"
        )
    start, end = opens[0].start(), closes[0].end()
    if end <= start:
        raise CheckError(
            f"{readme_path}: the closing marker comes before the opening one"
        )
    return start, end


def report(readme_path: Path, found: str, wanted: str) -> list[str]:
    diff = difflib.unified_diff(
        found.splitlines(),
        wanted.splitlines(),
        fromfile=f"{readme_path} (as written)",
        tofile=f"{readme_path} (as the manifest declares)",
        lineterm="",
    )
    return [f"  {line}" for line in diff]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--datasets-dir", default="datasets", type=Path)
    parser.add_argument(
        "--write",
        action="store_true",
        help="regenerate each README's block from its manifest instead of checking it",
    )
    args = parser.parse_args(argv)

    manifests = sorted(args.datasets_dir.glob("*/arcform.yaml"))
    if not manifests:
        print(
            f"protocol readme: no {args.datasets_dir}/*/arcform.yaml — nothing was "
            f"checked, which is a fault and not a pass",
            file=sys.stderr,
        )
        return EXIT_ERROR

    disagreements: list[str] = []
    faults: list[str] = []
    written: list[Path] = []
    examined = 0

    for manifest_path in manifests:
        readme_path = manifest_path.with_name("README.md")
        try:
            if not readme_path.is_file():
                raise CheckError(
                    f"{manifest_path} has no README.md beside it. Every Protocol "
                    f"describes itself to a reader; a manifest with no README is not "
                    f"skipped here, it is a failure"
                )
            steps = steps_of(manifest_path)
            text = readme_path.read_text(encoding="utf-8")
            start, end = locate_block(readme_path, text, create=args.write)
        except CheckError as exc:
            # COLLECTED, NOT RETURNED. Returning on the first fault made the count
            # below unfalsifiable: every run either examined all of them or printed
            # nothing at all, so `examined` and `len(manifests)` could not differ and
            # a line claiming to distinguish the two was claiming nothing. Collecting
            # gives that line a value a broken tree can move, and it is the better
            # report besides — four datasets with four faults name four, not one.
            faults.append(f"{exc}")
            continue

        wanted = render(steps)
        found = text[start:end]
        # AFTER the block was read and compared, never before: this counts datasets
        # this run actually held to their manifest, which is the number the line
        # below is for.
        examined += 1

        if args.write:
            if found != wanted:
                head, tail = text[:start], text[end:]
                if start == end:
                    # Creating the block, not replacing one: give it a heading and a
                    # trailing newline. The replace path adds neither, or every run
                    # would push one more blank line into the file.
                    head = head.rstrip("\n") + "\n\n## The step list\n\n"
                    tail = "\n"
                readme_path.write_text(head + wanted + tail, encoding="utf-8")
                written.append(readme_path)
            continue

        if found != wanted:
            disagreements.append(
                f"{readme_path}: its step block is not the step list "
                f"{manifest_path} declares"
            )
            disagreements.extend(report(readme_path, found, wanted))

    # Printed on every run, pass or fail. A check that examined nothing and a check
    # that examined everything both exit 0, and this line is what tells them apart —
    # which is only true because the two numbers CAN differ, above.
    print(f"protocol readme: examined {examined} manifest(s) of {len(manifests)} found")
    for manifest_path in manifests:
        print(f"  {manifest_path}")

    if faults:
        print(
            f"\nprotocol readme: {len(faults)} of {len(manifests)} manifest(s) could "
            f"not be held to a README at all\n",
            file=sys.stderr,
        )
        for fault in faults:
            print(f"  {fault}", file=sys.stderr)
        return EXIT_ERROR

    if args.write:
        if written:
            print(f"\nprotocol readme: rewrote {len(written)} block(s)")
            for path in written:
                print(f"  wrote {path}")
        else:
            print("\nprotocol readme: every block was already what the manifest declares")
        return EXIT_OK

    if disagreements:
        print(
            f"\nprotocol readme: {examined} manifest(s) checked, and a README does "
            f"not match the Protocol it describes\n",
            file=sys.stderr,
        )
        for line in disagreements:
            print(line, file=sys.stderr)
        print(
            "\nprotocol readme: FAILED — regenerate with "
            "`python scripts/check_protocol_readme.py --write`",
            file=sys.stderr,
        )
        return EXIT_DISAGREEMENT

    print("\nprotocol readme: every README's step list is its manifest's step list")
    return EXIT_OK


if __name__ == "__main__":
    sys.exit(main())
